### ISSUE TITLE
Thanks for your greating work. Looking forward to open source soon.

### ISSUE THREAD

**Issue by drilistbox** [SJoJoK/3DGStream#1]

**Comment by SJoJoK** [comment]
Thanks for your interest in our project! We are excited for people who want to use our code. According to our release roadmap, we expect the code to be released around Jun. 2024.

**Comment by gaoyuchen2000** [comment]
Great work, looking forward to hearing your updates!

**Comment by SJoJoK** [comment]
We have created a private repository containing an unpolished version of our code as pre-release code, along with a simple guide in README for researchers to use. If you are interested in accessing this repository, please send an email from your affiliated institutional email address to [csjk@zju.edu.cn](mailto:csjk@zju.edu.cn) with a brief explanation of your need (e.g., working on a submission for NeurIPS or SIGGRAPH Asia) and your github account (username, full name, and/or email). We will provide you with the link to the repository and access permissions.
﻿
Also, an unpolished version of 3DGStream will appear in this repository soon. :)
