### ISSUE TITLE
I have two doubts ,

### ISSUE THREAD

**Issue by AnudhinaDhanabalan** [SJoJoK/3DGStream#18]

**Comment by AnudhinaDhanabalan** [comment]
i) I downloaded the FVV that you have provided in the 3dgstreamviewer and it is working ,but after i ran the extract
_fvv.py i did not get the config.json file in the NTCs folder?
ii) i have provided the model path containing the iteration 15000 ply file , but i my init_3dgs_ply file is not  getting  generated .can you please help me solve this error.

**Comment by SJoJoK** [comment]
1. For the missing config.json, I suggest modifying the extract_fvv.py script to copy the file automatically. We'll address this in a future release.

2. I need more details about the init_3dgs_ply file issue. Please specify the steps you followed and any error messages. Your current description doesn't give me a clear picture of what you are doing or what you expect to achieve.

**Comment by AnudhinaDhanabalan** [comment]
i provided the this as the path to the model path ""test/flame_steak_suite/flame_steak_init ""  and ran the train_frames.py , by running the above i got the seperate ply files under iteration 150  and 250, but i did not get the init_3dgs_ply file anywhere 

python train_frames.py --read_config --config_path test/flame_steak_suite/cfg_args.json -o 
temp/custom_op_stream -m test/flame_steak_suite/flame_steak_init -v dataset/flame_steak   --image images --first_load_iteration 15000 --quiet

this is what i ran

**Comment by SJoJoK** [comment]
Oh I see, the so-called init_3dgs_ply is actually test/flame_steak_suite/flame_steak_init/point_cloud/iteration_15000/point_cloud.ply, you can copy it to you fvv directory and rename it.

**Comment by AnudhinaDhanabalan** [comment]
thank you so much for the clarification.

**Comment by AnudhinaDhanabalan** [comment]
can you please tell me what to do to get the config.json file ?

**Comment by SJoJoK** [comment]
It's the `--ntc_conf_path` when you run train_frames.py. In this case, it's configs/cache/cache_F_4.json. You can take a look at test/flame_steak_suite/cfg_args.json and see what `ntc_conf_path` exactly is.

**Comment by AnudhinaDhanabalan** [comment]
thank youu so much !!!

**Comment by SJoJoK** [comment]
Glad to help:)
