### ISSUE TITLE
how to generate cfg_args.json and ntc_parms for our own dataset?

### ISSUE THREAD

**Issue by AnudhinaDhanabalan** [SJoJoK/3DGStream#19]
I am currently working to generayte 3dgstream for my own dataset, during the final step i am confused abt getting two things

**Comment by AnudhinaDhanabalan** [comment]
i) the cfg_args.json file inside the flame_steak_init, how to generate that for my own dataset?
ii) under the ntc folder there is a file named ntc_path_F_4.pth , it has been mentioned in the cfg_args.json file ,so if want my own file of that what should i do?
thanks in advance !!

**Comment by SJoJoK** [comment]
1. The cfg_args.json file is automatically generated based on the arguments you set during training. You need to adjust the arguments according to your dataset, and once training starts, the cfg_args.json file will be created in the output directory.

2. To create your own config of ntc, please refer to the documentation of tiny-cuda-nn.

**Comment by AnudhinaDhanabalan** [comment]
python train_frames.py --read_config --config_path  /METACHN/custom/custom_init/cfg_args.json -o /METACHN/custom/customoutput -m /METACHN/custom/custom_init  -v /METACHN/custom_ff2   --image images --first_load_iteration 15000 --quiet
,but it needs and asks for a cfg_args.json file if i run the above code

**Comment by SJoJoK** [comment]
dont specify `--read_config`

**Comment by SJoJoK** [comment]
Could you please read the README , our paper or just take a look at the provided cfg_args.json and try to understand why these error raise but not directly ask them in the issue? I think it's clear that you should specify `--sh_degree 1`

**Comment by AnudhinaDhanabalan** [comment]
okayy, thank you so much !
