### ISSUE TITLE
How could I get the frame000001 to frame000298?

### ISSUE THREAD

**Issue by zjxx** [SJoJoK/3DGStream#23]
As there is only the frame000000 in `3DGStream\test\flame_steak_suite` ,and the FVVs provided by [this repo](https://github.com/SJoJoK/3DGStreamViewer?tab=readme-ov-file) contain frame000000 to frame000298.I'm wondering how could I get 
the frame000001 to frame000298 to train?

**Comment by SJoJoK** [comment]
Please check the README and use the script we've provided.

**Comment by zjxx** [comment]
> Please check the README and use the script we've provided.

I'm sorry, but it may be 4-i steps. I don't understand what I should be expected to extract the frames from, as there is no script before step 4.

**Comment by SJoJoK** [comment]
> > Please check the README and use the script we've provided.
> 
> 
> 
> I'm sorry, but it may be 4-i steps. I don't understand what I should be expected to extract the frames from, as there is no script before step 4.

You should download the N3DV dataset first.

**Comment by zjxx** [comment]
> > > Please check the README and use the script we've provided.
> > 
> > 
> > I'm sorry, but it may be 4-i steps. I don't understand what I should be expected to extract the frames from, as there is no script before step 4.
> 
> You should download the N3DV dataset first.

thank u(
