### ISSUE TITLE
Questions about tcnn's dim

### ISSUE THREAD

**Issue by Zhaoyibinn** [SJoJoK/3DGStream#25]
Thank you for your attribution，but I have some questions about tcnn's dim. 
Since we only use 7dim of the output of tcnn，why the net is define as 8dim？
```
if training_args.only_mlp:
model=tcnn.Network(n_input_dims=3,n_output_dims=8,network_config=ntc_conf["network"]).to(torch.device("cuda"))
else:
model=tcnn.NetworkWithInputEncoding(n_input_dims=3, n_output_dims=8,encoding_config=ntc_conf["encoding"],network_config=ntc_conf["network"]).to(torch.device("cuda"))
```

```
resi=self.model(ntc_inputs)
masked_d_xyz=resi[:,:3]
masked_d_rot=resi[:,3:7]
```

**Comment by SJoJoK** [comment]
Hi,
In fact, this is a historical legacy problem. When I first started the experiments, I used the 8-dim output. Later, for convenience, I did not change the setting, but commented out the related lines instead. So that's why the NTC has 8-dim output but I only use 7 dims of them.

**Comment by Zhaoyibinn** [comment]
Thank you for your answer. Additionally, I have one more question:
May I ask if the multi-resolution hash you used is only used to estimate the transformation of Gaussian points, and did not use multi-resolution hash in the render process (it seems to store the scale, sh, and other information of all Gaussian points instead of using hash voxel interpolation)

**Comment by SJoJoK** [comment]
yes, the ntc is only used to transform the gaussians

**Comment by Zhaoyibinn** [comment]
Oh, okay, thank you very much for your answer ^^
