### ISSUE TITLE
what do you mean by "only the transformed ones carried into the next timestep."

### ISSUE THREAD

**Issue by NeutrinoLiu** [SJoJoK/3DGStream#3]
in the caption of figure 3 of your CVPR paper, you mentioned that "only the transformed ones carried into the next timestep". can you further elaborate this statement. 

for instance, gaussians in the time stamp t are:
S_t = {s1 .... sn}
you have derived transformations of your gaussians through MLP and derived new gaussians for the next moment:
B_t+1 = {b1 ... bm} where bi = si + △si
you also have your new additional gaussians:
A_t+1 = {a1 ... ak}
then for the next time stamp rendering, guassians are:
S_t+1 = {...B_t+1, ...A_t+1}

is this "only the transformed ones carried into the next timestep" means: 
- m < n
- or means only B_t+1 gets carried to the next time stamp (t+2 lets say), A_t+1 is not counted in? 

In another word, did you perform pruning and split for stage 1? or to say, the number of "basic" gaussians has never changed since timestamp 0 ?
~~Also want to make sure that, NTC is per-timestamp correct? means the total memory utilization will be sizeofNTC * timestamps~~

**Comment by SJoJoK** [comment]
> In another word, did you perform pruning and split for stage 1?”

No, we didn't.

> the number of "basic" gaussians has never changed since timestamp 0 ?

Yes.

**Comment by NeutrinoLiu** [comment]
> > In another word, did you perform pruning and split for stage 1?”
> 
> No, we didn't.
> 
> > the number of "basic" gaussians has never changed since timestamp 0 ?
> 
> Yes.

nice work. looking forward to your open source code.
