### ISSUE TITLE
The number of training iterations

### ISSUE THREAD

**Issue by xiao10ma** [SJoJoK/3DGStream#33]
Hi, Jiakai! Sorry to trouble you again.

You show the PSNR results related to training iterations in table 9. And it takes only 150 or 250 iterations to train every frame after the first frame.

But when I use the command similar to the one you mentioned in the README.md, it takes 30000 iterations to train a frame. Should I update the code?
```
python train_frames.py -o output/coffee_martini -m /data/duantong/mazipei/gaussian-splatting/output/e07f7538-7 -v /data/duantong/mazipei/3DGStream/dataset/coffee_martini --image images --first_load_iteration 30000 --sh_degree 1 --ntc_conf_path configs/cache/cache_F_4.json --ntc_path ntc/coffee_martini_ntc_params_F_4.pth --eval
```

**Comment by SJoJoK** [comment]
don't forget --read_config and --config_path

**Comment by xiao10ma** [comment]
Thank you, i should follow the hyper params as the `test/flame_steak_suite/cfg_args.json`
