### ISSUE TITLE
How much time it takes when training the first frame (e.g. t = 0)?

### ISSUE THREAD

**Issue by gwxxx** [SJoJoK/3DGStream#5]
Thanks for your great work! It takes about 12 seconds for per-frame training, but does it also take only 12 seconds for the first frame?

**Comment by SJoJoK** [comment]
Thanks for your interest in our work!
The Initialization (i.e., get the 3dgs of t=0) is a typical 3DGS training and it takes about 10-15 minutes.
Therefore, in fact, our training time for each subsequent frame only takes about 9 seconds, but when we calculate the average, we take into account the training time of init_3dgs, so the metric we show in our paper is 12s.

**Comment by gwxxx** [comment]
> Thanks for your interest in our work! The Initialization (i.e., get the 3dgs of t=0) is a typical 3DGS training and it takes about 10-15 minutes. Therefore, in fact, our training time for each subsequent frame only takes about 9 seconds, but when we calculate the average, we take into account the training time of init_3dgs, so the metric we show in our paper is 12s.

Thanks for your reply. I focus on NVS for static scenes, and I wonder are there any 3dgs based method with accelerated training time?

**Comment by SJoJoK** [comment]
Maybe you can take a look at this work https://github.com/city-super/Scaffold-GS, it converges in shorter time.

**Comment by gwxxx** [comment]
> Maybe you can take a look at this work https://github.com/city-super/Scaffold-GS, it converges in shorter time.

Thanks!

**Comment by SJoJoK** [comment]
Glad to help:)
