### ISSUE TITLE
gaussian_model.py Line743

### ISSUE THREAD

**Issue by PeggyWang19** [SJoJoK/3DGStream#6]
args.ntc_conf_path undefined?

**Comment by SJoJoK** [comment]
You should specify it in arguments, it's been defined in https://github.com/SJoJoK/3DGStream/blob/f0cea68ee792554007836a1e627f575ca67a98cf/arguments/__init__.py#L101

**Comment by SJoJoK** [comment]
I've just updated README to fix inaccurate information (`--ntc_conf`->`--ntc_conf_path`), sorry for any confusion caused.

**Comment by AnudhinaDhanabalan** [comment]
it is working, but i am getting this error now !!
 assert len(extra_f_names)==3*(self.max_sh_degree + 1) ** 2 - 3
AssertionError
