### ISSUE TITLE
Clarity on instructions

### ISSUE THREAD

**Issue by HarshitGupta29** [SJoJoK/3DGStream#9]
> Follow the instructions in [gaussian-splatting](https://github.com/graphdeco-inria/gaussian-splatting) to get a high-quality init_3dgs (sh_degree = 1) from the above colmap dataset, which will end-up like:

Final init_3dgs gaussian point cloud has sh_degree =3. Is this a typo or we should only train for 1k iterations to keep sh_degree equal to 1 ?

**Comment by SJoJoK** [comment]
This means that the `max_sh_degree` should be set to 1. We will clarify it in the README, sorry for any inconvenience.

**Comment by HarshitGupta29** [comment]
Thanks a lot!
